### ISSUE TITLE
M30 exceptions

### ISSUE THREAD

**Issue by stefhenry** [pdemarco925/homebridge-icomfort#14]
Would you please confirm which models are supported? I have a M30.
Thanks

```
[2021-12-3 06:19:28] [Config] Console v4.5.1 is listening on :: port 8080
(node:215) UnhandledPromiseRejectionWarning: StatusError: **Unauthorized**
    at ClientRequest.h.request (/usr/local/lib/node_modules/homebridge-icomfort/node_modules/bent/src/nodejs.js:133:23)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
```

**Comment by lukestein** [comment]
I believe that the iComfort S30/E30/M30 models may *not* be supported. There have been no updates to this repo including documentation in a while, unfortunately.

**Comment by gowtham1643** [comment]
Will there be any releases to support M30 ?

**Comment by Malonee93** [comment]
Yes please add support the the S30. I know there api is now available.

**Comment by suboray** [comment]
Please add support for M30...  I saw in the update that it most likely will not work with M30.  Has anyone actually tried?

**Comment by sconstantine** [comment]
Any update on S30/M30/E30 portal (which uses endpoint https://www.lennoxicomfort.com/account/login)?
